language: php

dist: xenial

cache:
    directories:
        - vendor
        - extra/*/vendor
        - $HOME/.composer/cache/files

env:
    global:
        - SYMFONY_PHPUNIT_DISABLE_RESULT_CACHE=1

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - echo memory_limit = -1 >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/travis.ini

install:
    - travis_retry composer install
    - ./vendor/bin/simple-phpunit install
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/cssinliner-extra && travis_retry composer install)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/html-extra && travis_retry composer install)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/inky-extra && travis_retry composer install)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/intl-extra && travis_retry composer install)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/markdown-extra && travis_retry composer install)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/string-extra && travis_retry composer install)

script:
    - ./vendor/bin/simple-phpunit
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/cssinliner-extra && ./vendor/bin/simple-phpunit)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/html-extra && ./vendor/bin/simple-phpunit)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/inky-extra && ./vendor/bin/simple-phpunit)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/intl-extra && ./vendor/bin/simple-phpunit)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/markdown-extra && ./vendor/bin/simple-phpunit)
    - ([[ $TRAVIS_PHP_VERSION = "nightly" ]] || cd extra/string-extra && ./vendor/bin/simple-phpunit)

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly
        # Drupal does not support 3.x yet
        #- stage: integration tests
        #  php: 7.3
        #  script: ./drupal_test.sh
